### ISSUE TITLE
Freeze when loading databases

### ISSUE THREAD

**Issue by ghost** [root670/CheatDevicePS2#16]
Version used = CheatDevice v1.6

When I loaded CheatDevice with my zipped cheat database, I was greeted with the prompt to specify whether the database should be RO/RW. I selected read-only and everything seemed fine. I added a cheat to my database and had CheatDevice generate a read-write database for me.  The database saved just fine and everything was ok until I rebooted my console and attempted to restart CheatDevice. I recieved an error prompt "Error loading read/write cheat database "CheatDatabase_RW.txt" and was unable to do anything because the software had crashed at this point.  I found that deleting the cheat history file temporarily stops the crash, however the error message is still displayed. The databases appear to be loaded just fine after confirming the prompt despite the error. This behavior continues every time a game is booted, or in other words, when the cheat history file is generated.

**Comment by root670** [comment]
Can you please paste the contents of CheatDevicePS2.ini and CheatDatabase_RW.txt? I believe this error is happening somewhere in ‘cheatsLoadDatabase()’, relating to how it determines if an error occurred. At a glance I think I accidentally caused it to exit prematurely if a cheat database was loaded successfully but no new games were added. Since the cheat you added was for a game that already existed in the RO database, the additional cheats should have been appended to the end of the game’s cheat list.

Give me a couple days and I should have a chance to check this out. Thanks for reporting the issue!

**Comment by ghost** [comment]
Here's the files.  Take your time, no rush.
[CheatDevicePS2 Files.zip](https://github.com/root670/CheatDevicePS2/files/3100806/CheatDevicePS2.Files.zip)

**Comment by root670** [comment]
Issue should be fixed. Please try the v1.6.1 release :)

**Comment by ghost** [comment]
You forgot to post the updated ELF.

**Comment by root670** [comment]
Whoops, just added it. Thanks for letting me know.
